export class NotaryPaymentLog {
    token!: any;
    flag!: any;
    invoiceNo!:string;
    extSearch!:string;
    secondCopyCheck!:string;
    obtainExt!:string;
    obtainSecondCpyTaking!:string;
    prepOfTitle!:string;
    photographyFees!:string;
    govStampDuty!:string;
    regFees!:string;
    transpotationFees!:string;
    notaryFees!:string;
    expServiceCharge!:string;
    refCommision!:string;
    postageCharge!:string;
    fullChargeOfServiceProvision!:string;
    firstAdvance!:string;
    secondAdvance!:string;
    thirdAdvance!:string;
    forthAdvance!:string;
    fifthAdvance!:string;
    finalPayment!:string;
    amountInArreas!:string;
    descriptionOfService!:string;
    pickUpDate!:string;
    dateOfSubmission!:string;
    dateOfMailing!:string;
    dateOfRegistration!:string;
    stampDuty!:string;
    totalAmount!:string;
}
